######################################################################
##
## Filename: drum_machine_SM_TB2.udo
## Created on: Thu Apr 18 17:22:43 Pacific Daylight Time 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
