######################################################################
##
## Filename: drum_machine_TB_SM.udo
## Created on: Wed Apr 10 16:21:43 Pacific Daylight Time 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
